"""Explicit fictional replies for the twenty demo suppliers; never impersonate Gmail delivery."""

import io
import re
import textwrap
from pathlib import Path

from sqlalchemy import select

from nova.inbox import ingest_message
from nova.models import Case, Draft, Message
from nova.workflow import audit, locked

DEMO_MAILBOX = "devstar4418@gcplab.me"
FIXTURES = Path(__file__).resolve().parent.parent / "examples" / "colleague-demo" / "replies"
TYPOS = {
    "recycled": "recylced",
    "renewable": "renewble",
    "polymer": "polymre",
    "product": "prodcut",
    "demonstration": "demonstation",
    "electricity": "electrcity",
    "packaging": "packagng",
    "maintenance": "maintenence",
    "annually": "anually",
}


def enabled_for(settings, case):
    return (
        settings.demo_auto_reply
        and settings.mail_mode == "gmail"
        and settings.gmail_supplier.casefold() == DEMO_MAILBOX
        and case.recipient.casefold() == DEMO_MAILBOX
        and re.fullmatch(r"DEMO20-(?:0[1-9]|1[0-9]|20)", case.supplier_id) is not None
        and case.nart == case.supplier_id + "-ARTICLE"
        and case.supplier_name.startswith("Demo ")
    )


def pdf_document(lines, *, scanned=False):
    from reportlab.pdfgen.canvas import Canvas

    stream = io.BytesIO()
    canvas = Canvas(stream, invariant=1)
    wrapped = [line for raw in lines for line in (textwrap.wrap(raw, 85) or [""])]
    for start in range(0, len(wrapped), 44):
        page = wrapped[start : start + 44]
        if scanned:
            from PIL import Image, ImageDraw, ImageFont
            from reportlab.lib.utils import ImageReader

            bitmap = Image.new("RGB", (1240, 1754), "white")
            draw = ImageDraw.Draw(bitmap)
            font = ImageFont.load_default(size=22)
            for i, line in enumerate(page):
                draw.text((70, 80 + i * 34), line, fill="black", font=font)
            canvas.drawImage(ImageReader(bitmap), 0, 0, width=595, height=842)
        else:
            canvas.setFont("Helvetica", 10)
            for i, line in enumerate(page):
                canvas.drawString(45, 790 - i * 16, line)
        canvas.showPage()
    canvas.save()
    return stream.getvalue()


def response_content(supplier_id):
    number = int(supplier_id[-2:])
    original = (FIXTURES / f"{supplier_id}.txt").read_text()
    answers = [line for line in original.splitlines() if line.startswith(supplier_id + "-F")]
    if not answers:
        raise ValueError("Demo response fixture is empty")
    # Alter answer spelling only; routing/field references and quantities remain intact.
    if number % 5 != 1:

        def misspell(line):
            key, value = line.split("=", 1)
            for good, typo in TYPOS.items():
                value = re.sub(r"\b" + good + r"\b", typo, value)
            return key + "=" + value

        answers = [misspell(line) for line in answers]
    marker = "SIMULATED SUPPLIER REPLY — generated by NOVA for the fictional DEMO20 scenario.\n"
    mode = (number - 1) % 5
    if mode == 0:
        return marker + "\nHello, here are our confirmed answers:\n" + "\n".join(answers), [], "plain text"
    if mode == 1:
        prose = [
            "For " + line.split("=", 1)[0] + ", we confirm: " + line.split("=", 1)[1] + "."
            for line in answers
        ]
        return (
            marker + "\nHelo team, sorry for the speling mistakes.\n\n" + "\n\n".join(prose),
            [],
            "free text with typos",
        )
    if mode == 2:
        return (
            marker + "\nPlease see the attatched text answers.",
            [("supplier-answers.txt", "\n".join(answers).encode())],
            "TXT attachment with typos",
        )
    if mode == 3:
        pdf = pdf_document(["FICTIONAL DEMO SUPPLIER EVIDENCE", *answers])
        return (
            marker + "\nPlease see our answers in the attached PDF.",
            [("supplier-evidence.pdf", pdf)],
            "PDF with typos",
        )
    if number == 20:
        pdf = pdf_document(["FICTIONAL DEMO - SCANNED EVIDENCE", *answers], scanned=True)
        return (
            marker + "\nOur scanned answer sheet is attached.",
            [("scanned-supplier-evidence.pdf", pdf)],
            "scanned PDF with typos",
        )
    split = max(1, len(answers) // 2)
    pdf = pdf_document(["FICTIONAL DEMO SUPPLIER EVIDENCE", *answers[split:]])
    return (
        marker + "\nThese answers are in the email; the rest are in the PDF:\n" + "\n".join(answers[:split]),
        [("additional-evidence.pdf", pdf)],
        "email plus PDF with typos",
    )


def simulate_reply_job(factory, settings, job_id, token, target_id):
    from nova.worker import own_job

    with factory.begin() as db:
        job = own_job(db, job_id, token)
        draft = db.get(Draft, target_id)
        case = locked(db, Case, draft.case_id)
        if not enabled_for(settings, case) or draft.status != "sent":
            job.status = "cancelled"
            return
        external_id = "demo-simulated:" + draft.id
        if db.scalar(select(Message.id).where(Message.external_id == external_id)):
            job.status = "done"
            return
        # If a real supplier already replied, do not insert an additional scripted answer.
        if db.scalar(
            select(Message.id).where(Message.case_id == case.id, Message.created_at >= draft.created_at)
        ):
            job.status = "cancelled"
            return
        body, attachments, scenario = response_content(case.supplier_id)
        reply = ingest_message(
            db, settings, case.id, external_id, case.recipient, body, attachments, "demo-simulator"
        )
        audit(db, "demo-simulator", "reply.simulated", reply["id"], scenario=scenario, draft_id=draft.id)
        job.status = "done"
